### ISSUE TITLE
Not enough timers.

### ISSUE THREAD

**Issue by Gnarflord** [fliegwerk/simple-timer#1]
Nice README though

**Comment by fussel178** [comment]
The clock is now ticking ^^
https://fliegwerk.github.io/simple-timer/

**Comment by Gnarflord** [comment]
100% more timer, I like it.

**Comment by pklaschka** [comment]
> 100% more timer, I like it.

🤔 

Before: 0 timers;
After: 1 timer;

Verifying statement of increment of 100 %...
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)
1/0 = ... (calculating)

Error: maximum recursion depth. Aborting...

Returning NaN.

---

(before anyone else reads this and believes I'm a total jerk: @Gnarflord and I are friends. This is a joke. Relax.

**Comment by Gnarflord** [comment]
> There is no such thing as maximum recusion depth. Only not enough RAM

-Some Lisp Programmer probably
